"""First Migration

Revision ID: a6dad7364592
Revises: 
Create Date: 2023-10-28 15:48:31.106535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6dad7364592'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buzzword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buzzword', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buzzword')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('major', sa.String(), nullable=True),
    sa.Column('instructor', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    op.drop_table('buzzword')
    # ### end Alembic commands ###
